# Generated by Django 5.2.5 on 2025-08-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('standardio', 'Standard I/O'), ('structural', 'Structural')], max_length=20)),
                ('prompt', models.TextField()),
                ('timeout_seconds', models.PositiveIntegerField(default=5)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('tests_json', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StructuralTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_source', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('code_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_tests', to='codequestions.codequestion')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structural_tests', to='sandbox.runtime')),
            ],
            options={
                'ordering': ['code_question_id', 'order', 'runtime__name'],
                'constraints': [models.UniqueConstraint(fields=('code_question', 'runtime'), name='unique_structural_test_per_runtime')],
            },
        ),
    ]
