# Generated by Django 5.2.5 on 2025-08-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequestion',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
