# Generated by Django 5.2.2 on 2025-08-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestion',
            name='compiled_at',
            field=models.DateTimeField(blank=True, help_text='When compiled_spec was last refreshed.', null=True),
        ),
        migrations.AddField(
            model_name='codequestion',
            name='compiled_spec',
            field=models.JSONField(blank=True, default=dict, help_text='Compiled spec used to generate test runners.'),
        ),
        migrations.AddField(
            model_name='codequestion',
            name='compiled_version',
            field=models.PositiveIntegerField(default=0, help_text='Bumped whenever compiled_spec changes.'),
        ),
    ]
