# Generated by Django 5.2.5 on 2025-08-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuraltest',
            options={},
        ),
        migrations.RemoveField(
            model_name='structuraltest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='structuraltest',
            name='order',
        ),
    ]
