# Generated by Django 5.2.5 on 2025-08-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('codequestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codequestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_questions', to='base.topic'),
        ),
    ]
