# Generated by Django 5.2.5 on 2025-08-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0002_alter_codequestion_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardioquestion',
            name='starter_code',
        ),
    ]
