# Generated by Django 5.2.2 on 2025-08-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0002_codequestion_compiled_at_codequestion_compiled_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestion',
            name='compiled_runner_cache',
            field=models.JSONField(blank=True, default=dict, help_text='Cache of rendered test runner code per language. Format: {lang: {version, generator_version, content}}'),
        ),
    ]
