# Generated by Django 5.2.2 on 2025-08-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0003_codequestion_compiled_runner_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestion',
            name='function_name',
            field=models.CharField(blank=True, help_text="Name of the function to call for function-style questions (e.g., 'add')", max_length=100),
        ),
    ]
