# Generated by Django 5.2.2 on 2025-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0004_codequestion_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequestion',
            name='starter_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
