# Generated by Django 5.2.2 on 2025-08-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0005_codequestion_starter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codequestion',
            name='language',
        ),
    ]
