# Generated by Django 5.2.2 on 2025-08-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0006_remove_codequestion_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codequestion',
            name='function_name',
        ),
        migrations.RemoveField(
            model_name='codequestion',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='codequestion',
            name='test_style',
        ),
        migrations.AddField(
            model_name='codequestion',
            name='yaml_spec',
            field=models.TextField(default='type: standardIo\ndescription: Placeholder problem.\ntests: []', help_text='The full problem definition in YAML format, including tests.'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CodeTestCase',
        ),
    ]
