# Generated by Django 5.2.5 on 2025-08-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0007_remove_codequestion_function_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codequestion',
            name='starter_code',
        ),
        migrations.AlterField(
            model_name='codequestion',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(default=256, help_text='Max RAM (in MB) Docker container may use.'),
        ),
        migrations.AlterField(
            model_name='codequestion',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=2, help_text='Max seconds a student submission may run in Docker.'),
        ),
    ]
