# Generated by Django 5.2.2 on 2025-08-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('file_extension', models.CharField(max_length=16)),
                ('syntax_highlighter_mode', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('docker_image', models.CharField(max_length=200)),
                ('compile_command', models.CharField(blank=True, max_length=200)),
                ('run_command', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('default_entry_filename', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtimes', to='sandbox.language')),
            ],
            options={
                'ordering': ['language__name', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('language',), name='one_default_runtime_per_language')],
            },
        ),
    ]
