# Generated by Django 5.2.2 on 2025-08-28 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequestions', '0001_initial'),
        ('sandbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('timeout', 'Timeout'), ('oom', 'Out of Memory'), ('sandbox_error', 'Sandbox Error'), ('unknown', 'Unknown')], max_length=20)),
                ('summary', models.JSONField(default=dict)),
                ('junit_xml', models.TextField(blank=True)),
                ('stdout_tail', models.TextField(blank=True)),
                ('stderr_tail', models.TextField(blank=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=5)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('student_code', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='codequestions.codequestion')),
                ('runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='sandbox.runtime')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
