# Generated by Django 5.2.5 on 2025-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='assets_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='language',
            name='canonical_test_filename',
            field=models.CharField(blank=True, help_text='Canonical teacher test filename (e.g., tests.py, Tests.java).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='compile_command',
            field=models.CharField(blank=True, help_text='Optional compile/build command template.', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='solution_filename',
            field=models.CharField(default='solution', help_text='Base filename of the student’s solution without extension.', max_length=100),
        ),
        migrations.AddField(
            model_name='language',
            name='test_command',
            field=models.CharField(blank=True, help_text='Command to execute tests.', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='test_file_exts',
            field=models.CharField(blank=True, help_text='Comma-separated list of allowed test file extensions (e.g., .py,.pyw)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='test_framework',
            field=models.CharField(blank=True, choices=[('unittest', 'unittest'), ('pytest', 'pytest'), ('junit', 'JUnit'), ('jest', 'Jest'), ('gtest', 'GoogleTest')], help_text='Framework automatically used for teacher test files.', max_length=32, null=True),
        ),
    ]
