# Generated by Django 5.2.5 on 2025-08-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_language_assets_allowed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
